# ==============================================================================
# ABTR Equivalent-full core calculation
# Application: Griffin
# POC: Shikhar Kumar (kumars at anl.gov)
# If using or referring to this model, please cite as explained in
# https://mooseframework.inl.gov/virtual_test_bed/citing.html
# ==============================================================================

# This input file is automatically generated by the Griffin [MCC3CrossSection] block when generating the 33 group SFR cross section library
# - User should define heterogeneous RGMB core mesh in [Mesh] block or as separate input file
# - User should set Mesh/eqv_core/input to name of heterogeneous RGMB CoreMeshGenerator mesh
# - User should make sure boundary sidesets (outer_core, top, and bottom) are defined
#   in either TransportSystems/VacuumBoundary or TransportSystems/ReflectingBoundary
#   but not both
# - Optionally, a coarse mesh can be defined at the end of this Mesh block by the user to run Griffin with CMFD
# See online documentation or 'tests' file for the command line arguments to pass to do this
# Adding command line arguments from the input is coming in MOOSE FY24
# TODO User should define heterogeneous RGMB core mesh in [Mesh] block or as separate input file
# TODO User should set Mesh/eqv_core/input to name of heterogeneous RGMB CoreMeshGenerator mesh

[Mesh]
  [eqv_core]
    type = EquivalentCoreMeshGenerator
    input = het_core
    target_geometry = full_hom
  []
  [block_numbering]
    type = ElementIDToSubdomainID
    input = 'eqv_core'
    extra_element_id_name = 'material_id'
  []
  data_driven_generator = eqv_core
[]

[GlobalParams]
  is_meter = false
  plus = true
  library_file = 'mcc3xs.xml'
  library_name = 'ISOTXS-neutron'
[]

[TransportSystems]
  particle = neutron
  equation_type = eigenvalue
  G = 33
  ReflectingBoundary = 'outer_core top bottom'
  VacuumBoundary = 'outer_core top bottom'
  [dfem_sn]
    scheme = DFEM-SN
    family = L2_LAGRANGE
    order = FIRST
    AQtype = Gauss-Chebyshev
    NPolar = 2
    NAzmthl = 3
    NA = 1
    using_averaged_xs = true
    direction_major_ordering = true
    flux_moment_primal_variable = true
  []
[]

[Executioner]
  type = SweepUpdate
  richardson_rel_tol = 1e-6
  richardson_abs_tol = 1e-6
  richardson_max_its = 100
  richardson_value = eigenvalue
  inner_solve_type = GMRes
  max_inner_its = 4
  inner_tol = 1.e-3
  cmfd_acceleration = true
[]

[Materials]
  # Mapping of homogeneous subassembly ID to associated (heterogeneous assembly, axial ID) pairs:
  # 100: (fuel_assembly_1, 0), (fuel_assembly_2, 0), (fuel_assembly_3, 0)
  # 300: (fuel_assembly_1, 2), (fuel_assembly_2, 2), (fuel_assembly_3, 2)
  # 400: (fuel_assembly_1, 3), (fuel_assembly_2, 3), (fuel_assembly_3, 3)
  # 700: (control_assembly, 0), (control_assembly, 1)
  # 800: (control_assembly, 2), (control_assembly, 3)
  # 900: (reflector_assembly, 0), (reflector_assembly, 1), (reflector_assembly, 2), (reflector_assembly, 3)
  # 1000: (shielding_assembly, 0), (shielding_assembly, 1), (shielding_assembly, 2), (shielding_assembly, 3)
  [material_core_grid1]
    type = MixedMatIDNeutronicsMaterial
    isotopes = 'pseudo_REG'
    densities = '1.0'
    block = '100 300 400 700 800 900 1000'
    grid_names = 'Tcool'
    grid = '1'
  []
  # Mapping of homogeneous subassembly ID to associated (heterogeneous assembly, axial ID) pairs:
  # 200: (fuel_assembly_1, 1)
  # 500: (fuel_assembly_2, 1)
  # 600: (fuel_assembly_3, 1)
  [material_core_grid2]
    type = MixedMatIDNeutronicsMaterial
    isotopes = 'pseudo_REG'
    densities = '1.0'
    block = '200 500 600'
    grid_names = 'Tcool Tfuel'
    grid = '1 1'
  []
[]
